name: rice_trax
description: A new Flutter project for RiceTrax dashboard.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/rice_logo.jpg
    - assets/palay.jpg

pubspec.yaml:
  # This file is used to manage the dependencies and assets of the Flutter project.
  # It includes the necessary packages for the RiceTrax dashboard and defines the assets used in the application.
  # The versioning and environment constraints are also specified here.
  # Ensure to run `flutter pub get` after making changes to this file to update dependencies.